#ifndef FIREFLY_TEXTURE_TYPE_H_
#define FIREFLY_TEXTURE_TYPE_H_

enum FireflyTextureType
{
    FIREFLY_NORMAL_UNSELECTED,
    FIREFLY_NORMAL_SELECTED,
    FIREFLY_HIGHLIGHTED_UNSELECTED,
    FIREFLY_HIGHLIGHTED_SELECTED
};

#endif /* FIREFLY_TEXTURE_TYPE_H_ */